### ISSUE TITLE
Lab 12 doesn't have the correct hint

### ISSUE THREAD

**Issue by AbdelaliLaaguidi** [webpwnized/mutillidae#21]
i feel like the hint provided in "Lab 12: Command injection - Extracting User Accounts with Command Injection" isn't related to the lab i used sql injection and i found a list of users but none of them are in the list
[11:19:08] [INFO] fetching entries of column(s) 'username' for table 'accounts' in database 'mutillidae'
Database: mutillidae
Table: accounts
[23 entries]
+----------+
| username |
+----------+
| admin    |
| adrian   |
| john     |
| jeremy   |
| bryce    |
| samurai  |
| jim      |
| bobby    |
| simba    |
| dreveil  |
| scotty   |
| cal      |
| john     |
| kevin    |
| dave     |
| patches  |
| rocky    |
| tim      |
| ABaker   |
| PPan     |
| CHook    |
| james    |
| ed       |
+----------+

Which of these accounts exists on the Mutillidae Linux server?
--
 
slack                                  
ntp                                  
george                                  
fred                              	
cmdline

**Comment by webpwnized** [comment]
Patched in build 2.8.77
