### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments

### ISSUE THREAD

**Issue by m-naeem66622** [webpwnized/mutillidae#25]
Composer Version : `"2.3.9"`
PHP Version : `"8.1.6"`

When clicked for setting up new database the error occurred

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function CustomErrorHandler::getExceptionMessage(), 1 passed in C:\xampp\htdocs\classes\MySQLHandler.php on line 147 and exactly 2 expected in C:\xampp\htdocs\classes\CustomErrorHandler.php:134 Stack trace: #0 C:\xampp\htdocs\classes\MySQLHandler.php(147): CustomErrorHandler->getExceptionMessage(Object(mysqli_sql_exception)) #1 C:\xampp\htdocs\classes\MySQLHandler.php(162): MySQLHandler->doConnectToDatabase('127.0.0.1', 'root', 'mutillidae', 3306) #2 C:\xampp\htdocs\classes\MySQLHandler.php(104): MySQLHandler->doOpenDatabaseConnection() #3 C:\xampp\htdocs\set-up-database.php(20): MySQLHandler->__construct('owasp-esapi-php...', 0) #4 {main} thrown in C:\xampp\htdocs\classes\CustomErrorHandler.php on line 134`

**Comment by webpwnized** [comment]
Thanks. Fixed in version 2.8.83.
