### ISSUE TITLE
Warning: setcookie() expects parameter 3 to be integer

### ISSUE THREAD

**Issue by GitHubKane** [webpwnized/mutillidae#29]
Warning: setcookie() expects parameter 3 to be integer, array given in C:\xampp\htdocs\mutillidae1\index.php on line 137
![setcookie](https://user-images.githubusercontent.com/44124009/188971729-dab4610c-c19e-483a-b905-ad61ba84a5ea.JPG)

**Comment by webpwnized** [comment]
Once you update to PHP version 7.3 or higher, the warning should not show anymore. 

From [https://www.php.net/manual/en/function.setcookie.php](https://www.php.net/manual/en/function.setcookie.php): 

_**7.3.0 | An alternative signature supporting an options array has been added. This signature supports also the setting of the SameSite cookie attribute**_
