### ISSUE TITLE
Add a short instruction how to deploy this solution to kubernetes

### ISSUE THREAD

**Issue by 4c74356b41** [webpwnized/mutillidae#31]
You can use this as a starting point (works for me)
```
kubectl create deployment mutillidae-database --image="webpwnized/mutillidae:database"
kubectl create deployment mutillidae-ldap --image="webpwnized/mutillidae:ldap"
kubectl create deployment mutillidae-www --image="webpwnized/mutillidae:www"
kubectl create deployment mutillidae-databaseadmin --image="webpwnized/mutillidae:database_admin"
kubectl create deployment mutillidae-ldapadmin --image="webpwnized/mutillidae:ldap_admin"

kubectl expose deployment mutillidae-database --name=database --port=3306
kubectl expose deployment mutillidae-ldap --name=directory --port=389
kubectl expose deployment mutillidae-www --name=www --type=LoadBalancer --port=80
kubectl expose deployment mutillidae-databaseadmin --name=databaseadmin --type=LoadBalancer --port=80
kubectl expose deployment mutillidae-ldapadmin --name=ldapadmin --type=LoadBalancer --port=80
```

**Comment by webpwnized** [comment]
Hello. I created [this video](https://www.youtube.com/watch?v=uU1eEjrp93c) for the [mutillidae-terraform](https://github.com/webpwnized/mutillidae-terraform) project showing how to deploy to Kubernetes. However, you might add your contribution to the README on the mutillidae-terraform project. This project only encompasses the source code for the application itself, so the Kubernetes instruction will probably get lost here.

**Comment by 4c74356b41** [comment]
i saw the video, however it makes no sense to watch 18 and a half minute video for something that can be copy-pasted in under 30 seconds. I mean, i don't really care if you don't merge this, its your project, you are free to do whatever you like with it, however not having an obvious, concise, and "copypasteable" solution and instead having to watch an 18.5 minute video seems like a very bad choice.

**Comment by webpwnized** [comment]
Since the project is open source, any contributions are submitted as a Pull Request. For this improvement, please add the new instructions to the README on the [mutillidae-terraform](https://github.com/webpwnized/mutillidae-terraform) project. If a user without prior knowledge is able to use the instructions successfully, the Pull Request will be accepted, and the new instrcutions will be merged with the project.
