### ISSUE TITLE
File webservices/soap/ws-user-account.php variable $Encoder not defined

### ISSUE THREAD

**Issue by micheldiemer** [webpwnized/mutillidae#33]
function doXMLEncodeQueryResults($pUsername, $pQueryResult,
$pEncodeOutput){

Add
global $Encoder;

otherwise $Encoder->encodeForHTML($row->username) (in the while loop) generates an error

**Comment by webpwnized** [comment]
Thanks. Fixed in 2.10.8 which will be pushed by 10/18/2022
