### ISSUE TITLE
Cannot fork the repository

### ISSUE THREAD

**Issue by micheldiemer** [webpwnized/mutillidae#34]
When I try to fork I get an error message

failed to fork: HTTP 403: Description cannot be more than 350 characters 

gh repo fork git@github.com:webpwnized/mutillidae.git
failed to fork: HTTP 403: Description cannot be more than 350 characters (https://api.github.com/repos/webpwnized/mutillidae/forks)

**Comment by webpwnized** [comment]
I reduced the number of characters below 350; however, this is a bug in GitHub itself. The user interface allows more than 350 characters without issue. The API is out of sync with the user interface. GitHub needs to address that bug.
