### ISSUE TITLE
About mutillidae II

### ISSUE THREAD

**Issue by sammy2201** [webpwnized/mutillidae#39]
Can someone provide the precise number of vulnerabilities in Mutillidae II for me to compare manually? Alternatively, could someone present a list of the actual vulnerabilities?

**Comment by webpwnized** [comment]
The list of vulnerabilities is listed in Mutillidae in the Documentation menu. Also, each page has the "Help" button that shows the vulnerabilities on that page. Please add any additional documentation you would like, then submit a pull request.
